# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deployDev:
    name: "Deploy to Test Environment"
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: development
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.HEROKU_EMAIL}}
          # Your Heroku API Key
          api_key: ${{secrets.HEROKU_API_TOKEN}}
          # Your Heroku App Name
          app_name: ${{ secrets.APP_NAME}}
          
  testAPIDev:
  
    name: "Run API Tests"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: development    
    
    needs: deployDev
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
    
      - name: TestDev
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
        uses: anthonyvscode/newman-action@v1.1
        
        with:
          # Postman API key
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          # Collection to use
          collection: tests/postman/postmancollection.json
          # Environment to use
          environment: tests/postman/environments/development.json
          # Path to CSV or JSON data file
          iterationData: tests/postman/calc-test-data.csv
        
  deployStaging:

    name: "Deploy to Staging Environment"
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: staging
    
    needs: testAPIDev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.HEROKU_EMAIL}}
          # Your Heroku API Key
          api_key: ${{secrets.HEROKU_API_TOKEN}}
          # Your Heroku App Name
          app_name: ${{ secrets.APP_NAME}}

  UAT:

    name: "Run Users Acceptance Tests"

  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: staging    
    
    needs: deployStaging
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2    
    
      - name: TestDev
        # You may pin to the exact commit or the version.
        # uses: matt-ball/newman-action@0659e9b8d056c0d03d94e1dbfce380512088b566
        uses: anthonyvscode/newman-action@v1.1
        
        with:
          # Postman API key
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
          # Collection to use
          collection: tests/postman/postmancollection.json
          # Environment to use
          environment: tests/postman/environments/staging.json
          # Path to CSV or JSON data file
          iterationData: tests/postman/calc-test-data.csv
  
  deployToProd:

    name: "Deploy to Production"
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: production
    
    needs: UAT

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Deploy to Heroku
        uses: mtsmachado8/heroku-deploy@v2.0.3
        with:
          # Email Linked to your Heroku Account
          email: ${{ secrets.HEROKU_EMAIL}}
          # Your Heroku API Key
          api_key: ${{secrets.HEROKU_API_TOKEN}}
          # Your Heroku App Name
          app_name: ${{ secrets.APP_NAME}}
